import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer/footer';
import ClientSideProviderTest from '@/components/ClientSideProviderTest';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: {
		default: 'NextJS.14 Home Page',
		template: '%s | Next.JS 14',
	},
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico',
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ClientSideProviderTest>
					<div className='container'>
						<Navbar />
						{children}
						<Footer />
					</div>
				</ClientSideProviderTest>
			</body>
		</html>
	);
}
